version: 2
jobs:

  build:
    docker:
      - image: ruby:latest
    steps:
      - run: apt-get update && apt-get install ssh git
      - checkout
      - run:
          name: Setup locales
          command: |
            apt-get update && apt-get install -y locales ;
            locale-gen C.UTF-8 && /usr/sbin/update-locale LANG=C.UTF-8 ;
            echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen ;
      - run:
          name: Setup Jekyll
          command: |
            cd /root/project ;
            gem install bundler ;
            mkdir -p .bundle-cache
            bundle install --path=.bundle-cache ;
      - run:
          name: Build site
          command: |
            # Set default locale for the environment
            export LC_ALL=C.UTF-8 ;
            export LANG=en_US.UTF-8 ;
            export LANGUAGE=en_US.UTF-8 ;
            bundle exec jekyll build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build