version: 2
jobs:

  build:
    docker:
      - image: jekyll/jekyll:latest
    steps:
      - run:
          name: Install prerequisites
          command: |
            apk --no-progress update ;
            apk --no-progress add git 
      - checkout
      - run: bundle install 
      - run: bundle exec jekyll build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build